global using System.Reflection;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using CronJobScheduling.DataStore.Data;
global using CronJobScheduling.DataStore.Data.Migrator;
global using CronJobScheduling.DataStore.Models;
global using CronJobScheduling.DataStore.Repositories;
