# Run docker container:
#   docker compose up --remove-orphans
#
# Server login credentials:
#   username=root
#   password=pasSworD
#
# Server connection string:
#   "Server=localhost; Port=4200; Username=root; Password=pasSworD; Database=cronjob_db;"
#
# Using psql for debugging:
#   docker-compose exec -u postgres db bash
#
# Open database adminer:
#    http://localhost:4300
#
# Documentation:
#   https://www.postgresql.org/docs
#   https://www.adminer.org
#   https://hub.docker.com/_/postgres
#   https://hub.docker.com/_/adminer
#   https://github.com/docker-library/docs/tree/master/postgres

version: '3.2'

services:

  db:
    image: postgres:15.1
    container_name: blog-cronjob-npgsql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pasSworD
    ports:
      - 4200:5432

  adminer:
    image: adminer:4.8.1
    container_name: blog-cronjob-adminer
    restart: always
    depends_on:
      - db
    ports:
      - 4300:8080
