name: .NET

on:
  push:
    branches:
    - main
    - feature/**
  pull_request:
    branches:
    - main
    - feature/**
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd src/
        dotnet restore CronJobScheduling.sln
    - name: Build
      run: |
        cd src/
        dotnet build CronJobScheduling.sln --no-restore
    - name: Test
      run: |
        cd src/
        dotnet test CronJobScheduling.sln --no-build --verbosity normal
